### ISSUE TITLE
Docs: Add Contributing.md file

### ISSUE THREAD

**Issue by KerinPithawala** [s-ayush2903/KeepItClean#52]
I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
Can I work on this?

**Comment by myselfdeepdas** [comment]
I WOULD LIKE TO CONTRIBUTE ON YOUR PROJECT ,TELL ME WHICH TYPE OF "Contributing.md" FILE YOU WANT .GIVE ME SUJJESTION REAGARDING YOUR VIEWS,SO I CAN APPLY THOSE CHANGES AND CONTRIBUTE SOMTHING ON YOUR PROJECT.

**Comment by s-ayush2903** [comment]
Sorry, it's not open for contributions : (
